# https://github.com/techno-tim/littlelink-server
version: "3.0"
services:
  littlelink-server:
    image: ghcr.io/techno-tim/littlelink-server:latest
    # dockerhub is also supported timothystewart6/littlelink-server
    # image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=Adrien Biencourt | Goodshort
      - META_DESCRIPTION=Software Developer | Homelab | Full Nerd | Drones | DYI
      - META_AUTHOR=Adrien Biencourt
      - LANG=en
      - META_INDEX_STATUS=all
      - OG_SITE_NAME=Adrien Biencourt | Goodshort
      - OG_TITLE=Adrien Biencourt | Goodshort
      - OG_DESCRIPTION=A Goodshort overview
      - OG_URL=https://goodshort.me
      - OG_IMAGE=https://media.licdn.com/dms/image/D4E03AQGzY608Go2w8g/profile-displayphoto-shrink_800_800/0/1669803232177?e=1683158400&v=beta&t=wL-fjQw8jVpNcn912Q7Pxg1Utp_58LSn0pIGftV1WAA # From Twitter
      - OG_IMAGE_WIDTH=400
      - OG_IMAGE_HEIGHT=400
      # - GA_TRACKING_ID=G-XXXXXXXXXX
      - THEME=Dark
      - FAVICON_URL=https://pbs.twimg.com/profile_images/1027153532124835841/HUzoX0Q6_200x200.jpg
      - AVATAR_URL=https://pbs.twimg.com/profile_images/1027153532124835841/HUzoX0Q6_200x200.jpg
      - AVATAR_2X_URL=https://pbs.twimg.com/profile_images/1027153532124835841/HUzoX0Q6_400x400.jpg
      - AVATAR_ALT=Adrien Biencourt Profile Pic
      - NAME=Adrien Biencourt
      - BIO=A simple landing page to connect with me!
      # use ENV variable names for order, listed buttons will be boosted to the top
      - BUTTON_ORDER=LINKED_IN,RESUME,GITHUB,EMAIL,REDDIT,INSTAGRAM,FPV,FACEBOOK,YOUTUBE,TWITTER
      # you can render an unlimited amount of custom buttons by adding 
      # the CUSTOM_BUTTON_* variables and by using a comma as a separator.
      - CUSTOM_BUTTON_TEXT=FPV Instagram,Resume
      - CUSTOM_BUTTON_URL=https://www.instagram.com/goodshort_fpv,https://goodshort.github.io/react-ultimate-resume/
      - CUSTOM_BUTTON_COLOR=#000000,#67917a
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff,#ffffff
      - CUSTOM_BUTTON_ALT_TEXT=Dedicated Instagram for FPV and RC hobby,Interactive resume
      - CUSTOM_BUTTON_NAME=FPV,RESUME
      - CUSTOM_BUTTON_ICON=fab fa-instagram,fa-solid fa-file
      - GITHUB=https://github.com/goodshort
      - TWITTER=https://twitter.com/agoodshort
      - INSTAGRAM=https://www.instagram.com/goodshort_
      - YOUTUBE=https://www.youtube.com/channel/UCKlBz7E2RNi7krQwpRgZPcA
      - LINKED_IN=https://www.linkedin.com/in/adrien-biencourt
      - REDDIT=https://www.reddit.com/user/agoodshort
      - EMAIL=adrien.goodshort@gmail.com
      - EMAIL_TEXT=Email me
      # - TWITCH=https://l.technotim.live/twitch
      # - DISCORD=https://l.technotim.live/discord
      # - TIKTOK=https://l.technotim.live/tiktok
      - FACEBOOK=https://www.facebook.com/agoodshort/
      # - PATREON=https://l.technotim.live/patreon
      - FOOTER=Adrien Biencourt © 2023
    ports:
      - 3000:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
